# vim: set ft=make et :

default:
    @just --choose

compile_bpf target:
    clang -c -target bpf -fno-stack-protector -o build/{{file_stem(target)}}.o {{target}}

compile:
    #!/usr/bin/env bash
    mkdir -p build
    for file in `ls *.c`; do
        just compile_bpf ${file};
    done

