$(eval $(call addlib,appnginx))

APPNGINX_SRCS-y += $(APPNGINX_BASE)/main.c

APPNGINX_CFLAGS-$(CONFIG_APPNGINX_TRACING) += -mno-red-zone -pg -mrecord-mcount -mnop-mcount
LIBNGINX_CFLAGS-$(CONFIG_APPNGINX_TRACING) += -mno-red-zone -pg -mrecord-mcount -mnop-mcount
