# vim: set ft=make et :
#
APP := "build/sqlite_kvm-x86_64"

default:
    @just --choose

run:
    sudo qemu-system-x86_64 \
        -cpu host \
        -m 512M \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -fsdev local,id=myid2,path=$(pwd)/fs1,security_model=none \
        -device virtio-9p-pci,fsdev=myid2,mount_tag=fs1,disable-modern=on,disable-legacy=off \
        -initrd build/fs0.cpio \
        -kernel {{APP}} -nographic

run_9p:
    sudo qemu-system-x86_64 \
        -cpu host \
        -m 512M \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -fsdev local,id=myid,path=$(pwd)/fs0,security_model=none \
        -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
        -fsdev local,id=myid2,path=$(pwd)/fs1,security_model=none \
        -device virtio-9p-pci,fsdev=myid2,mount_tag=fs1,disable-modern=on,disable-legacy=off \
        -kernel {{APP}} -nographic

attach:
    sudo socat /tmp/port0 -
