# vim: set ft=make et :

default:
    @just --choose

run:
    sudo qemu-system-x86_64 \
        -cpu host \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -fsdev local,id=myid,path=$(pwd)/fs0,security_model=none \
        -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
        -kernel build/ushell_kvm-x86_64 -nographic

run_mmio:
    sudo qemu-system-x86_64 \
        -M microvm,x-option-roms=off,pit=on,pic=on,isa-serial=on,rtc=on,auto-kernel-cmdline=on,acpi=off,graphics=off \
        -cpu host \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial-device \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -fsdev local,id=myid,path=$(pwd)/fs0,security_model=none \
        -device virtio-9p-device,fsdev=myid,mount_tag=fs0 \
        -kernel build/ushell_kvm-x86_64 -nographic
