# vim: set ft=make et :

default:
    @just --choose

run:
    sudo qemu-system-x86_64 \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -kernel build/virtioconsole_kvm-x86_64 -nographic

run_mmio:
    sudo qemu-system-x86_64 \
        -M microvm \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial-device \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -kernel build/virtioconsole_kvm-x86_64 -nographic

run_pipe:
    -rm /tmp/port0
    mkfifo /tmp/port0
    sudo qemu-system-x86_64 \
        -enable-kvm \
        -chardev pipe,path=/tmp/port0,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,name=ushell \
        -kernel build/virtioconsole_kvm-x86_64 -nographic

run_noconsole:
    sudo qemu-system-x86_64 \
        -enable-kvm \
        -kernel build/virtioconsole_kvm-x86_64 -nographic
