# vim: set ft=make et :

APP := "build/sqlite3_backup_kvm-x86_64"

default:
    @just --choose

run:
    sudo qemu-system-x86_64 \
        -cpu host \
        -m 512M \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -fsdev local,id=myid,path=$(pwd)/fs0,security_model=none \
        -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
        -kernel {{APP}} -nographic

debug:
    sudo qemu-system-x86_64 \
        -gdb tcp::5678 \
        -cpu host \
        -m 512M \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -fsdev local,id=myid,path=$(pwd)/fs0,security_model=none \
        -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
        -kernel {{APP}} -nographic

gdb:
     gdb --eval-command="target remote :5678" \
         {{APP}}.dbg

test:
    gcc -o test main.c -lsqlite3

attach:
    sudo socat /tmp/port0 -

compile_cmd target:
    gcc -fPIC -c -o fs0/{{target}} fs0/{{target}}.c

compile_progs:
    @just compile_cmd 'call_backup'

gen_sym_txt:
    nm ./build/{{APP}}.dbg | cut -d ' ' -f1,3 > ./fs0/symbol.txt
