# vim: set ft=make et :

APP := "build/sqlite3_backup_kvm-x86_64"

default:
    @just --choose

run:
    sudo qemu-system-x86_64 \
        -cpu host \
        -m 512M \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -fsdev local,id=myid2,path=$(pwd)/fs1,security_model=none \
        -device virtio-9p-pci,fsdev=myid2,mount_tag=fs1,disable-modern=on,disable-legacy=off \
        -initrd build/fs0.cpio \
        -kernel {{APP}} -nographic


run_9p:
    sudo qemu-system-x86_64 \
        -cpu host \
        -m 512M \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -fsdev local,id=myid,path=$(pwd)/fs0,security_model=none \
        -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
        -fsdev local,id=myid2,path=$(pwd)/fs1,security_model=none \
        -device virtio-9p-pci,fsdev=myid2,mount_tag=fs1,disable-modern=on,disable-legacy=off \
        -kernel {{APP}} -nographic

debug:
    sudo qemu-system-x86_64 \
        -gdb tcp::5678 \
        -cpu host \
        -m 512M \
        -enable-kvm \
        -chardev socket,path=/tmp/port0,server=on,wait=off,id=char0 \
        -device virtio-serial \
        -device virtconsole,chardev=char0,id=ushell,nr=0 \
        -fsdev local,id=myid,path=$(pwd)/fs0,security_model=none \
        -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
        -kernel {{APP}} -nographic

gdb:
     gdb --eval-command="target remote :5678" \
         {{APP}}.dbg

test:
    gcc -o test main.c -lsqlite3

attach:
    sudo socat /tmp/port0 -

compile_cmd_wmpk target:
    gcc -DHAS_MPK -I../common/include -fPIC -c -o fs1/{{target}} fs1/{{target}}.c

compile_cmd target:
    gcc -I../common/include -fPIC -c -o fs1/{{target}} fs1/{{target}}.c

compile_progs:
    @just compile_cmd_wmpk 'empty'
    @just compile_cmd_wmpk 'hello'
    @just compile_cmd_wmpk 'perf'
    @just compile_cmd_wmpk 'call_backup'
    @just compile_cmd_wmpk 'generate_table'

compile_progs_nowmpk:
    @just compile_cmd 'call_backup'
    @just compile_cmd 'generate_table'

gen_sym_txt:
    nm {{APP}}.dbg | cut -d ' ' -f1,3 > ./fs1/symbol.txt

help:
  # how to confirm that the backup works:
  # in the uk-sqlite prompt run the following queries:
  # CREATE TABLE foo(bar INT);
  # INSERT INTO foo (bar) VALUES (1);
  # INSERT INTO foo (bar) VALUES (5);
  # then attach ushell, load symbol.txt and run call_backup
  # now you can upload fs0/dump to http://www.sqliteonline.net/ and inspect the dump
