//
// Created by ken on 25.05.23.
//

#ifndef USHELL_TERMINAL_PARAMETERS_H
#define USHELL_TERMINAL_PARAMETERS_H

#define USHELL_TERMINAL_PROMPT "> "

#define MOUNT_INFO_RESPONSE_PREFIX "mount-info"
#define MOUNT_INFO_COMMAND "ushell-" MOUNT_INFO_RESPONSE_PREFIX

#endif // USHELL_TERMINAL_PARAMETERS_H
