#ifndef USHELL_TERMINAL_PARAMETERS_H
#define USHELL_TERMINAL_PARAMETERS_H

#define USHELL_TERMINAL_PROMPT "> "

#define MOUNT_INFO_RESPONSE_PREFIX "mount-info"
#define MOUNT_INFO_COMMAND MOUNT_INFO_RESPONSE_PREFIX
#define BPF_HELPER_FUNCTION_INFO_RESPONSE_PREFIX "bpf-helper-info"
#define BPF_HELPER_INFO_COMMAND BPF_HELPER_FUNCTION_INFO_RESPONSE_PREFIX

#define BPF_PROG_TYPE_INFO_RESPONSE_PREFIX "bpf-prog-type-info"

#endif // USHELL_TERMINAL_PARAMETERS_H
