$(eval $(call addlib,appredis))

APPREDIS_SRCS-y += $(APPREDIS_BASE)/main.c

APPREDIS_CFLAGS-$(CONFIG_APPREDIS_TRACING) += -mno-red-zone -pg -mrecord-mcount -mnop-mcount
LIBREDIS_CFLAGS-$(CONFIG_APPREDIS_TRACING) += -mno-red-zone -pg -mrecord-mcount -mnop-mcount
