# vim: set ft=make et :

default:
    @just --choose

run:
    sudo taskset -c 0 qemu-system-x86_64 \
        -cpu host \
        -enable-kvm \
        -m 512M \
        -kernel build/hello_kvm-x86_64 -nographic

run_virtiofs:
    sudo taskset -c 0 qemu-system-x86_64 \
        -cpu host \
        -enable-kvm \
        -m 512M \
        -object memory-backend-memfd,id=mem,size=512M,share=on \
        -numa node,memdev=mem \
        -chardev socket,id=char1,path=/tmp/virtiofs.sock \
        -device vhost-user-fs-pci,queue-size=1024,chardev=char1,tag=fs0 \
        -kernel build/hello_kvm-x86_64 -nographic


