# vim: set ft=make et :

default:
    @just --choose

run target="helloworld.py":
    sudo qemu-system-x86_64 \
        -cpu host \
        -enable-kvm \
        -m 500M \
        -fsdev local,id=myid,path=$(pwd)/fs0,security_model=none \
        -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
        -append "-- {{target}}" \
        -kernel build/python_kvm-x86_64 -nographic

